version: "3.3"


services:

  cassandra-seed:
    image: cassandra:3.11.7
    environment:
      - "HEAP_NEWSIZE=1G"
      - "MAX_HEAP_SIZE=1G"

  cassandra1:
    image: cassandra:3.11.7
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed"
      - "HEAP_NEWSIZE=1G"
      - "MAX_HEAP_SIZE=1G"
    depends_on:
      - cassandra-seed